### ISSUE TITLE
Todo List Back-end 👨🏻‍🚀

### ISSUE THREAD

**Issue by DanielObara** [DanielObara/DesafioMeetApp#1]
# **First** Step Challenge Backend

- [x] Sucrase + Nodemon
- [x] ESLint + Prettier + EditorConfig
- [x] Sequelize (PostgresSQL)
- [x] Docker CE
- [x] Sequelize (PostgresSQL)

## Application

Below are the features you should add to your application.

### Auth
- [x] Allow a user to authenticate to your application using their email and password.
- [x] Authentication must be done using JWT.
- [x] Make input data validation

### Registering and Updating Users
- [x] Allow new users to sign up for your application using their name, email and password.
- [x] To update the password, the user must also submit a confirmation field with the same password.
- [x] Encrypt the user's password for security.
- [x]  Perform validation of input data

- [x] Authentication must be done using JWT.

# **Second** Step Challenge Backend

## Functionalities

Below are the features you should add to your application.

### File Management

- [x] Create a file upload route that registers in a table the path and file name and returns all data from the registered file.

### Meetup Management

- [x] The user can register meetups on the platform with meetup title, description, location, date and time and banner image. 
- [x] All fields are required.
- [x] Add a user_id field that stores the user ID that organizes the event.
- [x] It should not be possible to register meetups with dates that have passed.
- [x] The user must also be able to edit all meeting data that has not yet happened and that he is an organizer.
- [x] Create a route to list meetups that are organized by the logged in user.
- [x] The user must be able to cancel meetups organized by him that have not yet happened. Canceling must delete the meetup from the database.

### Meetup Signup

- [x] The user must be able to sign up for meetups they do not organize.
- [x] The user cannot subscribe to meetups that have already happened.
- [x] User cannot subscribe to the same meetup twice.
- [x] The user cannot sign up for two meetups that happen at the same time.
- [x] Whenever a user signs up for meetup, send an email to the organizer containing the data related to the registered user.

### Meetup Listing

- [x] Create a route to list filter meetups by date (not time).
- [x] The results of this listing should be paginated at 10 items per page. 

Below is an example call for the meetups listing route:

`` `
http: // localhost: 3333 / meetups? date = 2019-07-01 & page = 2
`` `

In this example, we will list page 2 of the meetups that will take place on July 1st.

- [x] In this listing also return the organizer data.

### Subscription Listing

- [x] Create a route to list the meetups to which the logged in user is subscribed.

- [x] Only list meetups that have not yet passed and rank closest meetups as first on the list.
